// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Replication.Infrastructure.Data.DataContext;

#nullable disable

namespace Replication.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601035013_addingTheSampleTables")]
    partial class addingTheSampleTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Replication.Domain.Entities.AnotherTransaction.AnotherTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnotherTransactions", (string)null);
                });

            modelBuilder.Entity("Replication.Domain.Entities.AnotherTransactionReplication.AnotherTransactionReplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnotherTransactionReplications", (string)null);
                });

            modelBuilder.Entity("Replication.Domain.Entities.Transaction.InfrastructureTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InfrastructureTransactions", (string)null);
                });

            modelBuilder.Entity("Replication.Domain.Entities.TransactionReplication.TransactionReplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransactionReplications", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
